Team-ComIT/SimTong-Backend

- .github/workflows/CI.yml
- .github/workflows/build.yml
- build.gradle.kts
- codecov.yml
- build.yml process 수정
- resolved #20
> merge: (#20) Jacoco 설정

- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/CustomFieldError.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/ErrorResponse.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/global/error/WebErrorHandler.kt
- ErrorResponse에 CustomFieldError 적용
- ConstraintViolationException ErrorResponse 메서드 호출시 인자로 exception 전달
- resolved #26
> merge: (#26) ErrorResponse 형식

- simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCase.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/dto/SignInRequest.kt
- simtong-application/src/test/kotlin/team/comit/simtong/user/usecase/SignInUseCaseTests.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/error/UserErrorCode.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/exception/DifferentPasswordException.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/ExceptionFilter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserJpaProvider.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserJpaRepository.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/WebSignInRequest.kt
- signIn end-point permission 설정
- signIn end-point handling
- BusinessException handling 로직
- resolved #32
> merge: (#32) 로그인 기능

- simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCase.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCase.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCaseTests.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/QueryMenuPort.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/menu/WebMenuAdapter.kt
- GET /menu 타입 형식 지정
- 메뉴 조회 security permission 설정
- resolved #84
> merge: (#84) 로그인 안된 상태에서 메뉴 조회

- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
- endpoint /users/password/initialization → /commons/password 변경
- permitAll 적용
- resolved #109
> merge: (#109) 비밀번호 초기화 변경 사항

- simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/ChangePasswordRequest.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangePasswordUseCase.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangePasswordUseCaseTests.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/WebChangePasswordRequest.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/WebResetPasswordRequest.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebSignUpRequest.kt
- #109 누락된 WebResetPasswordRequest commons 패키지로 이동
- 비밀번호 초기화 security config /commons/password → /commons/password/initialization
- 비밀번호 변경 security config /commons/password 
- resolved #103
> merge: (#103) 비밀번호 변경 기능

- .github/workflows/stage-cd.yml
- Dockerfile
- simtong-infrastructure/src/main/resources/application.yml
> merge: (#144) CD 구축

- Dockerfile
- simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/spi/CommandSchedulePort.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveSpotScheduleUseCase.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveSpotScheduleUseCaseTests.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/schedule/WebScheduleAdapter.kt
- delete schedule 쿼리 추가
- resolved #143
> merge: (#143) 지점 일정 삭제 기능

- simtong-application/src/test/kotlin/team/comit/simtong/domain/DomainPropertiesInitialization.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/CheckAuthCodeUseCaseTests.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCode.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCodeLimit.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/User.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainProperties.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainPropertiesPrefix.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/global/error/DomainErrorCode.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/global/exception/NotInitializationPropertiesException.kt
- simtong-domain/src/main/resources/domain.properties
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/config/DomainPropertiesConfig.kt
- simtong-infrastructure/src/main/resources/application.yml
- **기존 방식** : Domain Aggregate 객체 초기화 접근시 
Domain resources의 `domain.properties`를 읽어 Domain Aggregate 변수 초기화
- **문제점** : 배포 환경에서 Docker Image 실행 후 Domain Aggregate 초기화 접근시 `domain.properties`를 읽을 수 없는 문제 확인
- **해결 조건** : 환경변수 적용 가능, 외부 의존성 사용 불가, 개발 환경 영향 없음
- **해결방식** : Infra에서 ConfigurationProperties 사용, Map으로 변수 바인딩 → DomainProperties 초기화
- DomainProperties 파일 읽기 로직 삭제
- Domain의 domain.properties 파일 제거 → application.yml 파일로 property 이동
- DomainProperties test 초기화 에러 회피
- resolved #147
> merge: (#147) Domain Properties 에러

- simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/EntireSpotScheduleResponse.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/EntireSpotScheduleUseCase.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/spi/SpotPort.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/DomainPropertiesInitialization.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/EntireSpotScheduleUseCaseTests.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCode.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCodeLimit.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/QuerySchedulePort.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/ScheduleQuerySpotPort.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/vo/SpotSchedule.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainPropertiesPrefix.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/vo/SpotScheduleVo.kt
- simtong-infrastructure/src/main/resources/application.yml
- Domain Properties Prefix 변경
- resolved #149
> merge: (#149) 전체 지점 일정 조회

- simtong-application/src/test/kotlin/team/comit/simtong/domain/DomainPropertiesInitialization.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/CheckAuthCodeUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/ReissueTokenUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/SendAuthCodeUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/file/usecase/UploadImageUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/AddIndividualScheduleUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/AddSpotScheduleUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeIndividualScheduleUseCaseTest.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeSpotScheduleUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/EntireSpotScheduleUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveSpotScheduleUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/spot/usecase/ShowSpotListUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/AdminSignInUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeEmailUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeNicknameUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangePasswordUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeProfileImageUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeSpotUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/CheckEmailDuplicationUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/CheckMatchedAccountUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/CheckNicknameDuplicationUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/FindEmployeeNumberUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ResetPasswordUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/UserInfoUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/global/DomainPropertiesInitialization.kt
- simtong-application/src/test/kotlin/team/comit/simtong/global/annotation/SimtongTest.kt
- Domain Properties Initialization javadoc 삭제
- Application 계층 Test Case Import Domain Properties Initialization
- resolved #158
> merge: (#158) Domain Properties 초기화 전체 적용

- simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/QueryEntireSpotScheduleResponse.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/QueryIndividualSpotScheduleResponse.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/QueryEntireSpotScheduleUseCase.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/QueryIndividualSpotScheduleUseCase.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/QueryEntireSpotScheduleUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/QueryIndividualSpotScheduleUseCaseTests.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/QuerySchedulePort.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/domain/schedule/WebScheduleAdapter.kt
- Query String에 누락된 @NotNull 추가
- dateFilter로 한 달치 필터링 로직 분리
- EntireSpotSchedule~~ -> QueryEntireSpotSchedule~~
- resolved #166
> merge: (#166) 개인 + 일정 조회 API

- simtong-application/src/main/kotlin/team/comit/simtong/domain/file/spi/EmployeeCertificatePort.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/file/usecase/CheckEmployeeUseCase.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/file/usecase/CheckEmployeeUseCaseTests.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/error/FileErrorCode.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/exception/InvalidEmployeeException.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/spi/QueryEmployeeCertificatePort.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificateJpaRepository.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificatePersistenceAdapter.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
- 사원 확인 UseCase permission
- resolved #191
> merge: (#191) 이름, 사원번호 일치 여부 확인 API

- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePersistenceAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/RefreshTokenPersistenceAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificatePersistenceAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamPersistenceAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
- equals(=) 대신 return 사용
- 반환 타입 명시
- resolved #196
> merge: (#196) Aggregate Mapping 코드 스타일 변경 

- simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/QueryIndividualSpotScheduleResponse.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/QueryIndividualSpotScheduleUseCase.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/QueryIndividualSpotScheduleUseCaseTests.kt
- List 병합 작업 union 대신 plus
- resolved #204
> merge: (#204) 지점 + 개인 일정 보기 변경사항

- simtong-application/src/main/kotlin/team/comit/simtong/domain/file/spi/ParseEmployeeCertificateFilePort.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/file/usecase/RegisterEmployeeCertificateUseCase.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/CommandMenuPort.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuPort.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/ParseMenuFilePort.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/SaveMenuUseCase.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/file/usecase/RegisterEmployeeCertificateUseCaseTest.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/SaveMenuUseCaseTests.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/error/MenuErrorCode.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/exception/MenuAlreadyExistsSameMonthException.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/entity/MenuJpaEntity.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/mapper/MenuMapper.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/parser/ExcelFileAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/storage/AwsS3Adapter.kt
- simtong-infrastructure/src/main/resources/application-dev.yml
- simtong-infrastructure/src/main/resources/application-prod.yml
- simtong-infrastructure/src/test/kotlin/team/comit/simtong/thirdparty/storage/AwsS3AdapterTests.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/domain/menu/WebMenuAdapter.kt
- ParseFilePort -> ParseEmployeeCertificateFilePort
- SaveMenuUseCase permission
- external api 예외 발생 시 printStackTrace
- MenuJpaEntity 저장 시 persist 메서드 사용하도록 적용
- Batch Insert 적용
- resolved #188
> merge: (#188) 메뉴 저장 API

- simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/exception/AuthExceptions.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/UserJpaRepository.kt
- 이미 사용중인 사원번호 예외 추가
- resolved #228
> merge: (#228) 회원가입시 사원번호 검사 추가

- simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/CheckHolidayPeriodUseCase.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/CheckHolidayPeriodUseCaseTests.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPeriodPort.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPeriodPersistenceAdapter.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayJpaEntity.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
- **HolidayEntity** `HolidayStatus` 컬럼 속성 값 변경
- resolved #249
> merge: (#249) 휴무표 작성 기간 확인 기능

- simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/dto/AppointHolidayPeriodRequest.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/CommandHolidayPeriodPort.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/HolidayPeriodPort.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayPeriodUseCase.kt
- simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCase.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayPeriodUseCaseTests.kt
- simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryRemainAnnualUseCaseTests.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPeriodPersistenceAdapter.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/AppointHolidayPeriodWebRequest.kt
- simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/CancelHolidayWebRequest.kt
- 휴무표 작성 기간 저장 쿼리 추가
- CancelHolidayRequest → CancelHolidayWebRequest
- resolved #251
> merge: (#251) 휴무표 작성 기간 설정 기능

- simtong-domain/src/main/kotlin/team/comit/simtong/domain/notification/exception/NotificationExceptions.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/notification/model/Notification.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/notification/model/NotificationReceiver.kt
- simtong-domain/src/main/kotlin/team/comit/simtong/domain/notification/model/NotificationType.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/entity/NotificationJpaEntity.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/entity/NotificationReceiverJpaEntity.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/mapper/NotificationMapper.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/mapper/NotificationReceiverMapper.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/repository/NotificationJpaRepository.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/repository/NotificationReceiverRepository.kt
> merge: (#260) Notification Model 설계

- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/entity/EmployeeCertificateJpaEntity.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/entity/ScheduleJpaEntity.kt
- simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/UserJpaEntity.kt
> merge: (#275) Index 설정
