simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/Authority.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/BaseEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/BaseTimeEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/BaseUUIDEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/entity/SpotJpaEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/entity/TeamJpaEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/DeviceTokenJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/DeviceTokenJpaEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/UserJpaEntity.kt
simtong-presentation/src/main/resources/application.yml

merge: (#3) persistence model 설계

---

simtong-application/src/main/kotlin/team/comit/simtong/global/annotation/ReadOnlyUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/global/annotation/UseCase.kt
simtong-domain/src/main/kotlin/team/comit/simtong/global/annotation/Aggregate.kt
simtong-domain/src/main/kotlin/team/comit/simtong/global/annotation/DomainService.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/aop/TransactionAspect.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/aop/UseCaseScan.kt

merge: (#10) Annotation 구성 설계

---

simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/config/ConfigurationPropertiesConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/FilterConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityProperties.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/error/SecurityErrorCode.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/InvalidTokenException.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/principle/AuthDetails.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/principle/AuthDetailsService.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserJpaRepository.kt
simtong-presentation/src/main/resources/application.yml

- UserJpaRepository에 queryUserJpaEntityById 추가
- application.yml security 환경변수 추가
- resolved #9

merge: (#9) Security 설계

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/ReceiveTokenPort.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/config/RedisConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/FilterConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/JwtFilter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/error/SecurityErrorCode.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/ExpiredTokenException.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/UnexpectedTokenException.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/WrongTypeTokenException.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/GenerateJwtAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/JwtComponent.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/JwtParser.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePolicyRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/RefreshTokenRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodeEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodePolicyEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/RefreshTokenEntity.kt

merge: (#29) 주석 수정

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/ReceiveTokenPort.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/config/RedisConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/FilterConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/JwtFilter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/error/SecurityErrorCode.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/ExpiredTokenException.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/UnexpectedTokenException.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/WrongTypeTokenException.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/GenerateJwtAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/JwtComponent.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/JwtParser.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePolicyRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/RefreshTokenRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodeEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodePolicyEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/RefreshTokenEntity.kt

- Jwt 요소 수정
- Javadoc 수정
- resolved #23

merge: (#23) Jwt Filter 설계

---

.github/ISSUE_TEMPLATE/do.yml
.github/ISSUE_TEMPLATE/fix.yml
.github/ISSUE_TEMPLATE/refactor.yml

- do.yml, fix.yml 수정
- resolved #46

merge: (#46) Issue Template 변경

---

simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/mapper/SpotMapper.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/mapper/TeamMapper.kt

merge: (#70) 누락된 Adapter 설계

---

simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/error/MenuErrorCode.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/model/Menu.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/entity/MenuJpaEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/mapper/MenuMapper.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/mapper/TeamMapper.kt

- menu package 구조 정의
- TeamMapper 매핑 오류 수정
- resolved #62

merge: (#62) 직원 식당 메뉴표 Entity 설계

---

buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/SecurityPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/dto/MenuResponse.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuQueryUserPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuSecurityPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/QueryMenuPort.kt
simtong-infrastructure/build.gradle.kts
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/config/QuerydslConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/repository/MenuJpaRepository.kt
simtong-presentation/build.gradle.kts
simtong-presentation/src/main/kotlin/team/comit/simtong/menu/WebMenuAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/menu/dto/response/MenuResponse.kt

- /menu permission -> permit all
- resolved #80

merge: (#80) menu 조회

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/ChangeNicknameRequest.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangeNicknameUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeNicknameUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/error/AuthErrorCode.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/exception/UsedNicknameException.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/UserJpaRepository.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebChangeNicknameRequest.kt

- 닉네임 exists 쿼리 추가
- 사용된 닉네임 예외 처리
- Security Config /users/nickname
- resolved #94

merge: (#94) 닉네임 변경

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/ChangeEmailRequest.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangeEmailUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeEmailUseCaseTests.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebChangeEmailRequest.kt

- Security Config /users/email 추가
- resolved #96

merge: (#96) 이메일 변경 기능

---

simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCode.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCodeLimit.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/RefreshToken.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/model/Menu.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/model/Spot.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/team/model/Team.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/Authority.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt

- hasAnyRole → hasRole (하나의 권한만)
- Authority role 필드 추가
- aggregate data class 적용
- resolved #98

merge: (#98) Data class & Role 수정

---

simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/principle/AuthDetailsService.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/RefreshTokenPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodeEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodeLimitEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/RefreshTokenEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/AuthCodeLimitRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/AuthCodeRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/RefreshTokenRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/mapper/MenuMapper.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/mapper/TeamMapper.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/UserMapper.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/UserJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/email/AwsSESAdapter.kt

- Redis Repository Query 제거
- findByIdOrNull 사용
- Redis Persistence Entity data class 적용
- resolved #90

merge: (#90) Redis Repository 문제 해결

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/AuthCodeLimitPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/AuthCodePort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/CommandAuthCodeLimitPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/CommandAuthCodePort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/QueryRefreshTokenPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/RefreshTokenPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/spi/SpotPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/CommandUserPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserJwtPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangeSpotUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeSpotUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/spi/QueryAuthCodeLimitPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/spi/QueryAuthCodePort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuQueryUserPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuSecurityPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/QueryMenuPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/NickNamePort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/UserQueryAuthCodeLimitPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/UserQuerySpotPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/UserQueryTeamPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/UserSecurityPort.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebChangeSpotRequest.kt

- SPI doc에 'domain' 단어 추가
- changeProfileImage WebAdapter에 response status 추가
- resolved #115

merge: (#115) 지점 변경 기능

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/CheckNicknameDuplicationUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/CheckNicknameDuplicationUseCaseTests.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/dto/ErrorResponse.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt

- ErrorResponse 부분 실수 수정
- resolved #116

merge: (#116) 닉네임 중복 검사 기능

---

simtong-presentation/src/main/kotlin/team/comit/simtong/RegexUtil.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/WebChangePasswordRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/WebResetPasswordRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebChangeNicknameRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebSignUpRequest.kt

merge: (#122) regex util

---

simtong-presentation/src/main/kotlin/team/comit/simtong/admin/WebAdminAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/ChangePasswordWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/FindEmployeeNumberWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/ResetPasswordWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/response/FindEmployeeNumberWebResponse.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/email/WebEmailAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/email/dto/request/CheckAuthCodeWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/email/dto/request/SendAuthCodeWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/file/WebFileAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/file/dto/response/UploadImageListWebResponse.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/file/dto/response/UploadImageWebResponse.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/ChangeEmailWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/ChangeNicknameWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/ChangeProfileImageWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/ChangeSpotWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/SignInWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/SignUpWebRequest.kt

- Web ~ Request → ~ WebRequest
- Web ~ Response → ~ WebResponse
- resolved #123

merge: (#123) Request Dto 명 변경

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/dto/SpotResponse.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/spi/SpotPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/usecase/ShowSpotListUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/spot/usecase/ShowSpotListUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/spi/QuerySpotPort.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt

- security config /commons/spot
- resolved #128

merge: (#128) 지점 리스트 

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/CheckMatchedAccountRequest.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/CheckMatchedAccountUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/CheckMatchedAccountUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/UserJpaRepository.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/CheckMatchedAccountWebRequest.kt

- 이름 & 이메일 → 사원번호 & 이메일
- 계정 여부 확인 요소 변경
- name → employee number
- queryUserByNameAndEmail → queryUserByEmployeeNumberAndEmail
- resolved #130

merge: (#130) 사원번호 & 이메일 계정 여부 확인 수정

---

.gitignore
simtong-domain/src/main/resources/domain.properties

- application.yml ignore 제거
- domain.properties ignore 제거

merge: hotfix gitignore 수정

---

simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/storage/AwsS3Adapter.kt

**파일을 저장하던 예전 방식에서 변경되면서 누락된 부분**
- AwsS3Adapter InputS3 매개변수 file, fileName → file
- resolved #134

merge: (#134) InputS3 매개변수 정리

---

buildSrc/src/main/kotlin/Dependencies.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/spi/SchedulePort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/error/ScheduleErrorCode.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/model/Schedule.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/model/Scope.kt
simtong-infrastructure/build.gradle.kts
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/ScheduleJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/entity/ScheduleJpaEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/mapper/ScheduleMapper.kt

- 일정 애그리거트 추가
- 일정 Jpa Entity 추가
- 의존성 명칭 수정
- resolved #137

merge: (#137) 일정 Aggregate

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/CommandAuthCodeLimitPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/CommandAuthCodePort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/SecurityPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/AddSpotScheduleRequest.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/spi/CommandSchedulePort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/spi/SchedulePort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/AddSpotScheduleUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/CommandUserPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/AddSpotScheduleUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuQueryUserPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/ScheduleQueryUserPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/ScheduleSecurityPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/error/UserErrorCode.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/exception/NotEnoughPermissionException.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/Authority.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/schedule/WebScheduleAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/schedule/dto/request/AddSpotScheduleWebRequest.kt

- Command Port '저장을 요청하는' → '명령을 하는' javadoc 수정
- 최고 관리자 권한 추가 ROLE_SUPER
- 유저 권한 부족 Exception 추가
- resolved #139

merge: (#139) 지점 일정 추가 기능 설계

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/ChangeSpotScheduleRequest.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/spi/SchedulePort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/AddSpotScheduleUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeSpotScheduleUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/AddSpotScheduleUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeSpotScheduleUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/error/ScheduleErrorCode.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/exception/ScheduleNotFoundException.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/QuerySchedulePort.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/schedule/WebScheduleAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/schedule/dto/request/ChangeSpotScheduleWebRequest.kt

- 지점 일정 추가 권한 검사 로직 수정 `if (권한 검사 && 아이디 검사)` → `if (아이디 검사 && 권한 검사)`
- resolved #141

merge: (#141) 지점 일정 변경

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/AdminSignInUseCase.kt

- `Admin의 로그인` → `관리자의 로그인` javadoc 수정
- resolved #159

merge: (#159) 최고 관리자 로그인 오류 해결

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/global/DomainPropertiesInitialization.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/model/Spot.kt
simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainPropertiesPrefix.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/entity/MenuId.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/entity/MenuJpaEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/mapper/MenuMapper.kt
simtong-infrastructure/src/main/resources/application.yml

- 메뉴 엔티티 아이디 date → (date, spotId)
- 본점 HEAD_SHOP → Spot.HEAD_SHOP
- resolved #162

merge: (#162) 메뉴 엔티티 수정

---

simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/error/HolidayErrorCode.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/Holiday.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/HolidayType.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayId.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayJpaEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayMapper.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/repository/MenuJpaRepository.kt

- 메뉴 Jpa Repository id 변경
- resolved #164

merge: (#164) 휴무일 설계

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveIndividualScheduleUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveSpotScheduleUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveIndividualScheduleUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveSpotScheduleUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/error/ScheduleErrorCode.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/exception/DifferentScopeException.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/schedule/WebScheduleAdapter.kt

- 개인 일정 삭제 permission
- resolved #167

merge: (#167) 개인 일정 삭제 API

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/SecurityPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/CommandHolidayPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/HolidayPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/global/DomainPropertiesInitialization.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/error/HolidayErrorCode.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/exception/WeekHolidayLimitExcessException.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/Holiday.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/HolidayQueryUserPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/HolidaySecurityPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainPropertiesPrefix.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/QuerydslExtensionUtils.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
simtong-infrastructure/src/main/resources/application.yml
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/AppointHolidayWebRequest.kt

- 주 휴무일 조회 쿼리 추가
- Security Config : PUT, /dayoff, ROLE_COMMON
- resolved #169

merge: (#169) 휴무일 지정 설계

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/QueryEntireSpotScheduleUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/QueryEntireSpotScheduleUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/spot/usecase/ShowSpotListUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/QueryMenuPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/QuerySchedulePort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/ScheduleSecurityPort.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt

- holiday response gitkeep
- 지점 리스트 보기 testcase 세미콜론 삭제
- Schedule Security Port javadoc 수정
- 휴무일 PutMapping → PostMapping
- resolved #171

merge: (#171) Query 코드 리팩토링

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/CommandHolidayPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/CancelHolidayUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/CancelHolidayUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/error/HolidayErrorCode.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/exception/HolidayNotFoundException.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/CancelHolidayWebRequest.kt

- Security Config - DELETE, /work, ROLE_COMMON
- Holiday Not Found Exception 추가
- resolved #174

merge: (#174) 휴무일 또는 연차 취소 기능

---

simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/email/AwsSESAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/email/AwsSESConfig.kt

merge: (#177) 이메일 전송 비동기

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/dto/QueryIndividualHolidaysResponse.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/QueryIndividualHolidayUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryIndividualHolidayUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/global/DomainPropertiesInitialization.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/QueryMenuPort.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/WebErrorHandler.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/dto/ErrorResponse.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayJpaEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/schedule/WebScheduleAdapter.kt

- Holiday Entity Table 속성 수정 - VARCHAR(255) → VARCHAR(7)
- MissingServletRequestParameter 예외 처리 & 일정 Web Adapter @NotNull 제거
- DomainPropertiesInitialization 변경 - Pair(A, B) → A to B
- resolved #176

merge: (#176) 개인 휴무일 조회 설계

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ComparePasswordUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ComparePasswordUseCaseTests.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/WebCommonAdapter.kt

merge: (#182) 비밀번호 일치 여부 기능 설계

---

buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/file/spi/CommandEmployeeCertificatePort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/file/spi/EmployeeCertificatePort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/model/EmployeeCertificate.kt
simtong-infrastructure/build.gradle.kts
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificateJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificatePersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/entity/EmployeeCertificateJpaEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/mapper/EmployeeCertificateMapper.kt

- Excel File 관련 의존성 추가
- resolved #186

merge: (#186) 직원 명부 Entity 설계

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/AuthCodeLimitPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserCommandAuthCodeLimitPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ResetPasswordUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ResetPasswordUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeLimitPersistenceAdapter.kt

- userQuery~~ -> query~~
- resolved #184

merge: (#184) 인증 완료 후 인증코드 제한 삭제

---

simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/storage/AwsS3Adapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/WebFileAdapter.kt

- getResource 요청 시 URL이 변환됨
- MultipartFile → File 변환 시 Path 변경
- Upload Image 리팩토링
- resolved #199

merge: (#199) S3 등록된 이미지 접근 오류

---

LICENSE

소스코드 공개를 우선적으로 생각했습니다.
코드가 개선되어 더 좋은 코드가 생겼으면 하는 바람입니다.
- resolved #208

merge: (#208) License 추가

---

simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt

- 자세한 설명은 #212 
- resolved #212

merge: (#212) 개인 + 지점 별 일정 보기 오류 해결

---

SECURITY.md

merge: (#218) Security Policy 작성

---

simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/ChangePasswordWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/ResetPasswordWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/ChangeNicknameWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignUpWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/global/RegexUtil.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/global/RegexUtils.kt

- 정규식 재정의
- resolved #216
- 정규식이 틀릴 시 출력
> 닉네임 정규식 테스트 코드
> 결과
---
> 비밀번호 정규식 테스트 코드
> 결과

merge: (#216) 정규표현식 수정

---

simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/ResetPasswordWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignUpWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/global/RegexUtils.kt

- 사원 번호 Validation : Min & Max → Range 변경
- resolved #216

merge: (#216) 정규식 최적화

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/global/DomainPropertiesInitialization.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/exception/HolidayExceptions.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/Holiday.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainPropertiesPrefix.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/QuerydslExtensionUtils.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
simtong-infrastructure/src/main/resources/application.yml
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/AppointAnnualWebRequest.kt

- 연차 환경변수 Domain Properties 추가
- resolved #223

merge: (#223) 연차 지정 기능 설계

---

simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt

merge: (#232) api http method

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/CancelHolidayUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryIndividualHolidayUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/Holiday.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/HolidayPeriod.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/HolidayStatus.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPeriodPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayJpaEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayPeriodId.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayPeriodJpaEntity.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayPeriodMapper.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/repository/HolidayJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/repository/HolidayPeriodJpaRepository.kt

- 연차 지정 status → ANNUAL
- 휴무일 지정 status → WRITTEN
- resolved #235

merge: (#235) 휴무일 작성 기간 Aggregate 설계

---

.github/workflows/prod-cd.yml

merge: (#243) prod CD

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/CommandHolidayPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/ShareHolidayUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/ShareHolidayUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/ShareHolidayWebRequest.kt

- 휴무표 공유 API permission
- resolved #241

merge: (#241) 휴무표 공유 API

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/CancelHolidayUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCaseTests.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/CancelHolidayUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/exception/HolidayExceptions.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/HolidayStatus.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt

- 시간과 휴무일 유형에 따른 제약조건 추가
- 예외 문구 수정
- Holiday 변경 불가 예외 추가
- resolved #245

merge: (#245) 휴무일 & 연차 제약조건 추가

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/dto/QueryEmployeeHolidayResponse.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/QueryEmployeeHolidayUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryEmployeeHolidayUseCaseTests.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/HolidayQueryType.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/vo/EmployeeHoliday.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/vo/EmployeeHolidayVO.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/WebHolidayQueryType.kt

- 지점 직원 휴무일 보기 API permission
- resolved #248

merge: (#248) 지점 직원 휴무일 보기 API

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/dto/QueryMonthHolidayPeriodResponse.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/QueryMonthHolidayPeriodUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryMonthHolidayPeriodUseCaseTests.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt

merge: (#255) 휴무표 작성 기간 보기 기능

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/ChangeEmployeeHolidayUseCase.kt
simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/ChangeEmployeeHolidayUseCaseTests.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/ChangeEmployeeHolidayWebRequest.kt

- 지점 직원 휴무일 변경 API permission
- resolved #253

merge: (#253) 지점 직원 휴무일 변경 

---

simtong-infrastructure/src/main/resources/application-dev.yml
simtong-infrastructure/src/main/resources/application-prod.yml

redis password 설정

---

buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
simtong-infrastructure/build.gradle.kts
simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/notification/FcmAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/notification/FcmConfig.kt
simtong-infrastructure/src/main/resources/application-dev.yml
simtong-infrastructure/src/main/resources/application-prod.yml

- application-dev.yml, application-prod.yml에 fcm.value 프로퍼티 추가
- infrastructure 모듈에 firebase-admin dependency 추가
- resolved #178

merge: (#178) FCM 전송

---

simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/spi/CommandNotificationPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/spi/NotificationPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/spi/NotificationQueryUserPort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/spi/SendPushMessagePort.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/usecase/SendNotificationUseCase.kt
simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/notification/model/Notification.kt
simtong-domain/src/main/kotlin/team/comit/simtong/domain/notification/model/NotificationReceiver.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/NotificationPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/repository/NotificationReceiverJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/DeviceTokenJpaRepository.kt
simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/notification/FcmAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/notification/NotificationWebAdapter.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/notification/dto/SendNotificationWebRequest.kt
simtong-presentation/src/main/kotlin/team/comit/simtong/domain/notification/dto/WebNotificationType.kt

- 알림 전송시 type 추가
- NotificationReceiverRepository -> NotificationReceiverJpaRepository
- Notification, NotificationReceiver 생성자에 기본 값 적용
- resolved #261

merge: (#261) 알림 저장

---

.github/workflows/CI.yml
.github/workflows/build.yml
buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
simtong-infrastructure/build.gradle.kts
simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/ExceptionFilter.kt
simtong-infrastructure/src/main/resources/application.yml

merge: (#269) 에러 로깅
